clc; clear; close;

baseDir = fileparts(matlab.desktop.editor.getActiveFilename);
addpath(baseDir);
addpath(genpath(fullfile(baseDir, "ref_vehicle")));

load("roll_torque_to_right.mat")

vehicleParameter = struct( ...
    "trackwidth_F", struct( ...
        "value", 1.600, ...
        "unit", "m", ...
        "datatype", "double" ...
    ), ...
    "trackwidth_R", struct( ...
        "value", 1.614, ...
        "unit", "m", ...
        "datatype", "double" ...
    ) ...
);

poi = 7;
time = data.Time.data;
[~, idx] = min(abs(time - poi));
rollAngle = data.Car_Roll.data;

FzFL = data.Car_FzFL.data;
FzFR = data.Car_FzFR.data;
FzRL = data.Car_FzRL.data;
FzRR = data.Car_FzRR.data;

dFzF = (FzFL-FzFR)/2;
dFzR = (FzRL-FzRR)/2;

rollingStiffnesF = dFzF .* vehicleParameter.trackwidth_F.value ./ rollAngle;
rollingStiffnesR = dFzR .* vehicleParameter.trackwidth_R.value ./ rollAngle;
Mx = data.Car_Virtual_Trq_1_x.data;

totalRollStiffness = Mx ./ rollAngle;

totalRollStiffness_poi = totalRollStiffness(idx);
rollingStiffnesF_poi = rollingStiffnesF(idx);
rollingStiffnesR_poi = rollingStiffnesR(idx);

fprintf( ...
    "total roll stiffness:      %.4f Nm/rad\n" + ...
    "roll stiffness front axle: %.4f Nm/rad\n" + ...
    "roll stiffness rear axle:  %.4f Nm/rad\n", ...
    totalRollStiffness_poi, ...
    rollingStiffnesF_poi, ...
    rollingStiffnesR_poi ...
);

linewidth = 1.2;
fontSizeLabel = 11;
fontSizeLegend = 10;
figWidth  = 1600;
figHeight = 800;
f = figure( ...
    'Name','roll behavior', ...
    'NumberTitle','off', ...
    'Units','pixels', ...
    'Position',[100 100 figWidth figHeight] ...
);

tg = uitabgroup(f);
tab1 = uitab(tg, 'Title', 'roll torque / roll angle');
ax1 = axes('Parent', tab1);
yyaxis left
plot(time, Mx,'LineWidth',linewidth); hold on; grid on;
xlabel('time $[s]$','Interpreter','latex','FontSize',fontSizeLabel)
ylabel('roll torque $[Nm]$','Interpreter','latex','FontSize',fontSizeLabel)
xlim([min(time) max(time)])
ylim([min(Mx) max(Mx)])

yyaxis right
plot(time, rollAngle .* 180/pi,'LineWidth',linewidth); hold on; grid on;
xlabel('time $[s]$','Interpreter','latex','FontSize',fontSizeLabel)
ylabel('roll angle $[deg]$','Interpreter','latex','FontSize',fontSizeLabel)
xlim([min(time) max(time)])
ylim([min(rollAngle .* 180/pi) max(rollAngle .* 180/pi)])

legend({ ...
        '$M_{x}$', ...
        '$\phi$', ...
        }, ...
        'Interpreter','latex', ...
        'Location','northwest','FontSize',fontSizeLegend, ...
        'Box','off');

tab2 = uitab(tg, 'Title', 'lateral wheel loads');
ax2 = axes('Parent', tab2);
plot(time, FzFL, 'LineWidth',linewidth); hold on
plot(time, FzFR, 'LineWidth',linewidth);
plot(time, FzRL, 'LineWidth',linewidth);
plot(time, FzRR, 'LineWidth',linewidth); grid on
xlabel('time $[s]$','Interpreter','latex','FontSize',fontSizeLabel)
ylabel('lateral wheel load $[N]$','Interpreter','latex','FontSize',fontSizeLabel)
xlim([min(time) max(time)])

legend({ ...
        '$F_{zFL}$', ...
        '$F_{zFR}$', ...
        '$F_{zRL}$', ...
        '$F_{zRR}$', ...
        }, ...
        'Interpreter','latex', ...
        'Location','northwest','FontSize',fontSizeLegend, ...
        'Box','off');

tab3 = uitab(tg, 'Title', 'lateral wheel loads');
ax3 = axes('Parent', tab3);
plot(time, abs(dFzF), 'LineWidth',linewidth); hold on
plot(time, abs(dFzR), 'LineWidth',linewidth); grid on
xlabel('time $[s]$','Interpreter','latex','FontSize',fontSizeLabel)
xlim([min(time) max(time)])

legend({ ...
        '$\Delta{F_{zF}}$', ...
        '$\Delta{F_{zR}}$', ...
        }, ...
        'Interpreter','latex', ...
        'Location','northwest','FontSize',fontSizeLegend, ...
        'Box','off');

tab4 = uitab(tg, 'Title', 'rolling stiffness');
ax4 = axes('Parent', tab4);
plot(time, rollingStiffnesF, 'LineWidth',linewidth); hold on
plot(time, rollingStiffnesR, 'LineWidth',linewidth); grid on
plot(time, totalRollStiffness, 'LineWidth',linewidth);
ylabel('roll stiffness $[Nm/rad]$','Interpreter','latex','FontSize',fontSizeLabel)
xlabel('time $[s]$','Interpreter','latex','FontSize',fontSizeLabel)
xlim([min(time) max(time)])
ylim([min([rollingStiffnesF, rollingStiffnesR]) max(200000)])

legend({ ...
        '$c_{wF}$', ...
        '$c_{wR}$', ...
        '$c_{w}$', ...
        }, ...
        'Interpreter','latex', ...
        'Location','southeast','FontSize',fontSizeLegend, ...
        'Box','off');

