% -------------------------------------------------------------------
%  Generated by MATLAB on 11-May-2026 14:41:51
%  MATLAB version: 25.2.0.3177638 (R2025b) Update 5
% -------------------------------------------------------------------
                                                  

Fz_stat_FL = Simulink.Parameter;
Fz_stat_FL.Value = 3921.3656;
Fz_stat_FL.HasCoderInfo = false;
Fz_stat_FL.Description = '';
Fz_stat_FL.DataType = 'double';
Fz_stat_FL.Min = [];
Fz_stat_FL.Max = [];
Fz_stat_FL.DocUnits = 'N';

Fz_stat_FR = Simulink.Parameter;
Fz_stat_FR.Value = 3921.3656;
Fz_stat_FR.HasCoderInfo = false;
Fz_stat_FR.Description = '';
Fz_stat_FR.DataType = 'double';
Fz_stat_FR.Min = [];
Fz_stat_FR.Max = [];
Fz_stat_FR.DocUnits = 'N';

Fz_stat_RL = Simulink.Parameter;
Fz_stat_RL.Value = 3922.1269;
Fz_stat_RL.HasCoderInfo = false;
Fz_stat_RL.Description = '';
Fz_stat_RL.DataType = 'double';
Fz_stat_RL.Min = [];
Fz_stat_RL.Max = [];
Fz_stat_RL.DocUnits = 'N';

Fz_stat_RR = Simulink.Parameter;
Fz_stat_RR.Value = 3922.1267;
Fz_stat_RR.HasCoderInfo = false;
Fz_stat_RR.Description = '';
Fz_stat_RR.DataType = 'double';
Fz_stat_RR.Min = [];
Fz_stat_RR.Max = [];
Fz_stat_RR.DocUnits = 'N';

cog_height = Simulink.Parameter;
cog_height.Value = 0.604;
cog_height.HasCoderInfo = false;
cog_height.Description = '';
cog_height.DataType = 'double';
cog_height.Min = [];
cog_height.Max = [];
cog_height.DocUnits = 'm';

g = Simulink.Parameter;
g.Value = 9.806;
g.HasCoderInfo = false;
g.Description = '';
g.DataType = 'double';
g.Min = [];
g.Max = [];
g.DocUnits = 'm/s^2';

lF = Simulink.Parameter;
lF.Value = 1.466;
lF.HasCoderInfo = false;
lF.Description = '';
lF.DataType = 'double';
lF.Min = [];
lF.Max = [];
lF.DocUnits = 'm';

lR = Simulink.Parameter;
lR.Value = 1.509;
lR.HasCoderInfo = false;
lR.Description = '';
lR.DataType = 'double';
lR.Min = [];
lR.Max = [];
lR.DocUnits = 'm';

pitchAngle = Simulink.Parameter;
pitchAngle.Value = [0.00443372596055269; 0.0047201269853804; 0.0050065280102081; ...
                    0.00529292903503581; 0.00557933005986352; 0.00586573108469122; ...
                    0.00615213210951893; 0.00643853313434663; 0.00672493415917434; ...
                    0.00701133518400204; 0.00729773620882975; 0.00758413723365745; ...
                    0.00787053825848516; 0.00815693928331287; 0.00844334030814057; ...
                    0.00872974133296828; 0.00901614235779598; 0.00930254338262369; ...
                    0.00958894440745139; 0.0098753454322791; 0.0101617464571068; ...
                    0.0104481474819345; 0.0107345485067622; 0.0110209495315899; ...
                    0.0113073505564176; 0.0115937515812453; 0.011880152606073; ...
                    0.0121665536309007; 0.0124529546557284; 0.0127393556805562; ...
                    0.0130257567053839; 0.0133121577302116; 0.0135985587550393; ...
                    0.013884959779867; 0.0141713608046947; 0.0144577618295224; ...
                    0.0147441628543501; 0.0150305638791778; 0.0153169649040055; ...
                    0.0156033659288332; 0.0158897669536609; 0.0161761679784886; ...
                    0.0164625690033163; 0.016748970028144; 0.0170353710529717; ...
                    0.0173217720777994; 0.0176081731026271; 0.0178945741274549; ...
                    0.0181809751522826; 0.0184673761771103; 0.018753777201938; ...
                    0.0190401782267657; 0.0193265792515934; 0.0196129802764211; ...
                    0.0198993813012488; 0.0201857823260765; 0.0204721833509042; ...
                    0.0207585843757319; 0.0210449854005596; 0.0213313864253873; ...
                    0.021617787450215; 0.0219041884750427; 0.0221905894998704; ...
                    0.0224769905246981; 0.0227633915495259; 0.0230497925743536; ...
                    0.0233361935991813; 0.023622594624009; 0.0239089956488367; ...
                    0.0241953966736644; 0.0244817976984921; 0.0247681987233198; ...
                    0.0250545997481475; 0.0253410007729752; 0.0256274017978029; ...
                    0.0259138028226306; 0.0262002038474583; 0.026486604872286; ...
                    0.0267730058971137; 0.0270594069219414; 0.0273458079467691; ...
                    0.0276322089715968; 0.0279186099964245; 0.0282050110212523; ...
                    0.02849141204608; 0.0287778130709077; 0.0290642140957354; ...
                    0.0293506151205631; 0.0296370161453908; 0.0299234171702185; ...
                    0.0302098181950462; 0.0304962192198739; 0.0307826202447016; ...
                    0.0310690212695293; 0.031355422294357; 0.0316418233191847; ...
                    0.0319282243440124; 0.0322146253688401; 0.0325010263936678; ...
                    0.0327874274184955; 0.0330738284433233; 0.033360229468151; ...
                    0.0336466304929787; 0.0339330315178064; 0.0342194325426341; ...
                    0.0345058335674618; 0.0347922345922895; 0.0350786356171172; ...
                    0.0353650366419449; 0.0356514376667726; 0.0359378386916003; ...
                    0.036224239716428; 0.0365106407412557; 0.0367970417660834; ...
                    0.0370834427909111; 0.0373698438157388; 0.0376562448405665; ...
                    0.0379426458653942; 0.038229046890222; 0.0385154479150497; ...
                    0.0388018489398774; 0.0390882499647051; 0.0393746509895328; ...
                    0.0396610520143605; 0.0399474530391882; 0.0402338540640159; ...
                    0.0405202550888436; 0.0408066561136713; 0.041093057138499; ...
                    0.0413794581633267; 0.0416658591881544; 0.0419522602129821; ...
                    0.0422386612378098; 0.0425250622626375; 0.0428114632874652; ...
                    0.0430978643122929; 0.0433842653371207; 0.0436706663619484; ...
                    0.0439570673867761; 0.0442434684116038; 0.0445298694364315; ...
                    0.0448162704612592; 0.0451026714860869; 0.0453890725109146; ...
                    0.0456754735357423; 0.04596187456057; 0.0462482755853977; ...
                    0.0465346766102254; 0.0468210776350531; 0.0471074786598808; ...
                    0.0473938796847085; 0.0476802807095362; 0.0479666817343639; ...
                    0.0482530827591916; 0.0485394837840194; 0.0488258848088471; ...
                    0.0491122858336748; 0.0493986868585025; 0.0496850878833302; ...
                    0.0499714889081579; 0.0502578899329856; 0.0505442909578133; ...
                    0.050830691982641; 0.0511170930074687; 0.0514034940322964; ...
                    0.0516898950571241; 0.0519762960819518; 0.0522626971067795; ...
                    0.0525490981316072; 0.0528354991564349; 0.0531219001812626; ...
                    0.0534083012060903; 0.053694702230918; 0.0539811032557458; ...
                    0.0542675042805735; 0.0545539053054012; 0.0548403063302289; ...
                    0.0551267073550566; 0.0554131083798843; 0.055699509404712; ...
                    0.0559859104295397; 0.0562723114543674; 0.0565587124791951; ...
                    0.0568451135040228; 0.0571315145288505; 0.0574179155536782; ...
                    0.0577043165785059; 0.0579907176033336; 0.0582771186281613; ...
                    0.058563519652989; 0.0588499206778168; 0.0591363217026445; ...
                    0.0594227227274722; 0.0597091237522999; 0.0599955247771276; ...
                    0.0602819258019553; 0.060568326826783; 0.0608547278516107; ...
                    0.0611411288764384; 0.0614275299012661];
pitchAngle.HasCoderInfo = false;
pitchAngle.Description = '';
pitchAngle.DataType = 'double';
pitchAngle.Min = [];
pitchAngle.Max = [];
pitchAngle.DocUnits = 'rad';

pitchStiffness = Simulink.Parameter;
pitchStiffness.Value = [286621.759634828; 286644.842257284; 286407.773967962; ...
                        286374.136656328; 286600.567597571; 286901.705993052; ...
                        287109.323229665; 287190.659823331; 287245.018358591; ...
                        287344.728913005; 287488.533523694; 287631.863692162; ...
                        287761.853227503; 287866.497387494; 287970.829625024; ...
                        288087.66637387; 288222.423530708; 288361.280384856; ...
                        288496.054996294; 288632.160316116; 288772.111551563; ...
                        288912.248548618; 289040.88567235; 289187.369361627; ...
                        289323.606034439; 289474.404939597; 289621.575049367; ...
                        289765.47106707; 289889.96902524; 290001.210162603; ...
                        290106.027483785; 290221.473127394; 290353.135718342; ...
                        290469.661919595; 290586.401322526; 290722.301493718; ...
                        290824.744205224; 290936.184492928; 291062.662708901; ...
                        291200.366548715; 291389.100146545; 291587.665782402; ...
                        291761.433839246; 291906.734229549; 292078.780625232; ...
                        292348.252492718; 306432.474476975; 319773.575553752; ...
                        314575.674704745; 307792.370597038; 308653.856210852; ...
                        312246.180384968; 313065.104552531; 311700.059203013; ...
                        311032.770652735; 311638.454417453; 312274.796317702; ...
                        312380.403558105; 313511.604639463; 322536.296212064; ...
                        324702.973721329; 320622.488897657; 319537.303126707; ...
                        321405.996994609; 322395.973151045; 321797.423801687; ...
                        321395.381838842; 321791.266432875; 322152.006541286; ...
                        322231.811908455; 322213.823045904; 322849.035450574; ...
                        334766.851466425; 338506.79131874; 332393.089827944; ...
                        331530.271814643; 334497.910992901; 335066.116682909; ...
                        333812.965803833; 333738.576600587; 334496.745629882; ...
                        334688.951634682; 334497.667223369; 334592.464435446; ...
                        334832.433111533; 337208.262042783; 353820.782627891; ...
                        352113.459540232; 345180.565290356; 348199.997613915; ...
                        350843.461045394; 349017.464000097; 348458.297091146; ...
                        349546.761227148; 349747.330076217; 349405.913315111; ...
                        349551.956724404; 349879.280480376; 349890.778454964; ...
                        349969.382700487; 358688.238337734; 375485.67497411; ...
                        363993.565209804; 363347.628526186; 369001.71450384; ...
                        366735.757891375; 365406.8052491; 367142.033287893; ...
                        367033.857260049; 366576.444296329; 366905.003211679; ...
                        367162.695632063; 367072.532225194; 367174.204590119; ...
                        367281.707154236; 367477.152971532; 381494.261785917; ...
                        394998.844963755; 379907.012696458; 387036.554684262; ...
                        388281.097866663; 384459.300173943; 386925.299571314; ...
                        386863.144205431; 386134.487437016; 386900.160673467; ...
                        386730.080008285; 386785.625243138; 386987.476484381; ...
                        387036.567474048; 387086.653074446; 387203.26009712; ...
                        387278.179189375; 387920.995171853; 420043.400613775; ...
                        402483.312829689; 407200.185831783; 410268.43933026; ...
                        405394.82416415; 409141.935711187; 407492.982204635; ...
                        407896.51475603; 408315.750787872; 407859.622942295; ...
                        408258.017042769; 408198.068934178; 408317.176758605; ...
                        408350.151316056; 408405.663879512; 408397.33591142; ...
                        408372.804234088; 408451.558961705; 408557.578305987; ...
                        420158.230666075; 437150.317452758; 423250.339536077; ...
                        434943.990815377; 426757.679748082; 431634.627333503; ...
                        428907.525347493; 430496.474731827; 429958.561969104; ...
                        430233.579110935; 430148.966545783; 430143.015384615; ...
                        430220.437878188; 430359.597929488; 430562.904247657; ...
                        430660.577136368; 430780.763898625; 430886.22949828; ...
                        430978.959892885; 431236.019638899; 431508.556255084; ...
                        431574.948192388; 431699.901447438; 467857.504453395; ...
                        442765.776597423; 459643.35269551; 449548.587827503; ...
                        455200.959714307; 452275.285179138; 454045.913219995; ...
                        453314.382113952; 453815.608419985; 453826.470209945; ...
                        453932.13904406; 454125.35855117; 453928.002318723; ...
                        453847.966086145; 453581.867339882; 453440.136219668; ...
                        453126.093694606; 453074.718486349; 452782.12145749; ...
                        452759.396865049; 452438.671049305; 452558.118643181; ...
                        452209.993429366; 452113.97625663];
pitchStiffness.HasCoderInfo = false;
pitchStiffness.Description = '';
pitchStiffness.DataType = 'double';
pitchStiffness.Min = [];
pitchStiffness.Max = [];
pitchStiffness.DocUnits = 'N*m/rad';

pitch_inertia = Simulink.Parameter;
pitch_inertia.Value = 2180.5;
pitch_inertia.HasCoderInfo = false;
pitch_inertia.Description = '';
pitch_inertia.DataType = 'double';
pitch_inertia.Min = [];
pitch_inertia.Max = [];
pitch_inertia.DocUnits = 'kg * m^2';

pitching_coefficient = Simulink.Parameter;
pitching_coefficient.Value = -0.002;
pitching_coefficient.HasCoderInfo = false;
pitching_coefficient.Description = '';
pitching_coefficient.DataType = 'double';
pitching_coefficient.Min = [];
pitching_coefficient.Max = [];
pitching_coefficient.DocUnits = '1';

rdyn = Simulink.Parameter;
rdyn.Value = 0.309;
rdyn.HasCoderInfo = false;
rdyn.Description = '';
rdyn.DataType = 'double';
rdyn.Min = [];
rdyn.Max = [];
rdyn.DocUnits = 'm';

reference_area = Simulink.Parameter;
reference_area.Value = 2.4;
reference_area.HasCoderInfo = false;
reference_area.Description = '';
reference_area.DataType = 'double';
reference_area.Min = [];
reference_area.Max = [];
reference_area.DocUnits = 'kg / m^3';

rho = Simulink.Parameter;
rho.Value = 1.2;
rho.HasCoderInfo = false;
rho.Description = '';
rho.DataType = 'double';
rho.Min = [];
rho.Max = [];
rho.DocUnits = 'm^2';

rollStiffness_F = Simulink.Parameter;
rollStiffness_F.Value = -66168.4036;
rollStiffness_F.HasCoderInfo = false;
rollStiffness_F.Description = '';
rollStiffness_F.DataType = 'double';
rollStiffness_F.Min = [];
rollStiffness_F.Max = [];
rollStiffness_F.DocUnits = 'N*m/rad';

rollStiffness_R = Simulink.Parameter;
rollStiffness_R.Value = -79058.3706;
rollStiffness_R.HasCoderInfo = false;
rollStiffness_R.Description = '';
rollStiffness_R.DataType = 'double';
rollStiffness_R.Min = [];
rollStiffness_R.Max = [];
rollStiffness_R.DocUnits = 'N*m/rad';

sprung_mass = Simulink.Parameter;
sprung_mass.Value = 1373.3;
sprung_mass.HasCoderInfo = false;
sprung_mass.Description = '';
sprung_mass.DataType = 'double';
sprung_mass.Min = [];
sprung_mass.Max = [];
sprung_mass.DocUnits = 'kg';

tire = Simulink.Parameter;
saveVarsTmp{1} = struct;
saveVarsTmp{1}.MDI_Header = struct;
saveVarsTmp{1}.MDI_Header.FILE_VERSION = 2;
saveVarsTmp{1}.Model = struct;
saveVarsTmp{1}.Model.USE_MODE = 14;
saveVarsTmp{1}.Dim = struct;
saveVarsTmp{1}.Dim.UNLOADED_RADIUS = 0.3185;
saveVarsTmp{1}.Dim.WIDTH = 0.205;
saveVarsTmp{1}.Dim.RIM_RADIUS = 0.1905;
saveVarsTmp{1}.Dim.RIM_WIDTH = 0.1524;
saveVarsTmp{1}.Dim.ASPECT_RATIO = 0.6;
saveVarsTmp{1}.Vertical = struct;
saveVarsTmp{1}.Vertical.VERTICAL_STIFFNESS = 236700;
saveVarsTmp{1}.Vertical.VERTICAL_DAMPING = 50;
saveVarsTmp{1}.Vertical.BREFF = 5;
saveVarsTmp{1}.Vertical.DREFF = 0.3;
saveVarsTmp{1}.Vertical.FREFF = 0.1;
saveVarsTmp{1}.Vertical.FNOMIN = 6500;
saveVarsTmp{1}.Range = struct;
saveVarsTmp{1}.Range.KPUMIN = -0.3;
saveVarsTmp{1}.Range.KPUMAX = 0.3;
saveVarsTmp{1}.Range.ALPMIN = -0.1745;
saveVarsTmp{1}.Range.ALPMAX = 0.1745;
saveVarsTmp{1}.Range.CAMMIN = -0.1047;
saveVarsTmp{1}.Range.CAMMAX = 0.1047;
saveVarsTmp{1}.Range.FZMIN = 400;
saveVarsTmp{1}.Range.FZMAX = 8500;
saveVarsTmp{1}.Scale = struct;
saveVarsTmp{1}.Scale.LFZO = 1;
saveVarsTmp{1}.Scale.LCX = 1;
saveVarsTmp{1}.Scale.LMUX = 1;
saveVarsTmp{1}.Scale.LEX = 1;
saveVarsTmp{1}.Scale.LKX = 1;
saveVarsTmp{1}.Scale.LHX = 1;
saveVarsTmp{1}.Scale.LVX = 1;
saveVarsTmp{1}.Scale.LGAX = 1;
saveVarsTmp{1}.Scale.LCY = 1;
saveVarsTmp{1}.Scale.LMUY = 1;
saveVarsTmp{1}.Scale.LEY = 1;
saveVarsTmp{1}.Scale.LKY = 1;
saveVarsTmp{1}.Scale.LHY = 1;
saveVarsTmp{1}.Scale.LVY = 1;
saveVarsTmp{1}.Scale.LGAY = 1;
saveVarsTmp{1}.Scale.LTR = 1;
saveVarsTmp{1}.Scale.LRES = 1;
saveVarsTmp{1}.Scale.LGAZ = 1;
saveVarsTmp{1}.Scale.LXAL = 1;
saveVarsTmp{1}.Scale.LYKA = 1;
saveVarsTmp{1}.Scale.LVYKA = 1;
saveVarsTmp{1}.Scale.LS = 1;
saveVarsTmp{1}.Scale.LSGKP = 1;
saveVarsTmp{1}.Scale.LSGAL = 1;
saveVarsTmp{1}.Scale.LGYR = 1;
saveVarsTmp{1}.Scale.LMX = 1;
saveVarsTmp{1}.Scale.LVMX = 1;
saveVarsTmp{1}.Scale.LMY = 1;
saveVarsTmp{1}.Long = struct;
saveVarsTmp{1}.Long.PCX1 = 1.6055;
saveVarsTmp{1}.Long.PDX1 = 1.1703;
saveVarsTmp{1}.Long.PDX2 = -0.081328;
saveVarsTmp{1}.Long.PDX3 = 0;
saveVarsTmp{1}.Long.PEX1 = 0.53409;
saveVarsTmp{1}.Long.PEX2 = -0.019956;
saveVarsTmp{1}.Long.PEX3 = 0.18089;
saveVarsTmp{1}.Long.PEX4 = 2.9951E-7;
saveVarsTmp{1}.Long.PKX1 = 36.411;
saveVarsTmp{1}.Long.PKX2 = 0.12615;
saveVarsTmp{1}.Long.PKX3 = 0.51289;
saveVarsTmp{1}.Long.PHX1 = 0;
saveVarsTmp{1}.Long.PHX2 = 0;
saveVarsTmp{1}.Long.PVX1 = 0;
saveVarsTmp{1}.Long.PVX2 = 0;
saveVarsTmp{1}.Long.RBX1 = 18.456;
saveVarsTmp{1}.Long.RBX2 = 16.314;
saveVarsTmp{1}.Long.RCX1 = 1.091;
saveVarsTmp{1}.Long.REX1 = 0;
saveVarsTmp{1}.Long.REX2 = 0;
saveVarsTmp{1}.Long.RHX1 = 0.0058715;
saveVarsTmp{1}.Long.PTX1 = 1.5;
saveVarsTmp{1}.Long.PTX2 = 0.180096;
saveVarsTmp{1}.Long.PTX3 = -0.15;
saveVarsTmp{1}.OverTurn = struct;
saveVarsTmp{1}.OverTurn.QSX1 = 0.00023155;
saveVarsTmp{1}.OverTurn.QSX2 = 0.51574;
saveVarsTmp{1}.OverTurn.QSX3 = 0.046399;
saveVarsTmp{1}.Lat = struct;
saveVarsTmp{1}.Lat.PCY1 = 2.1322;
saveVarsTmp{1}.Lat.PDY1 = 1.0283;
saveVarsTmp{1}.Lat.PDY2 = -0.16758;
saveVarsTmp{1}.Lat.PDY3 = -1.5821;
saveVarsTmp{1}.Lat.PEY1 = 0.33443;
saveVarsTmp{1}.Lat.PEY2 = -1.8733;
saveVarsTmp{1}.Lat.PEY3 = -0.13136;
saveVarsTmp{1}.Lat.PEY4 = -11.677;
saveVarsTmp{1}.Lat.PKY1 = -20.505;
saveVarsTmp{1}.Lat.PKY2 = 2.0284;
saveVarsTmp{1}.Lat.PKY3 = 0.89994;
saveVarsTmp{1}.Lat.PHY1 = 0.0031377;
saveVarsTmp{1}.Lat.PHY2 = 0.00051596;
saveVarsTmp{1}.Lat.PHY3 = 0.039251;
saveVarsTmp{1}.Lat.PVY1 = 0.026365;
saveVarsTmp{1}.Lat.PVY2 = -0.0062119;
saveVarsTmp{1}.Lat.PVY3 = -0.41389;
saveVarsTmp{1}.Lat.PVY4 = -0.048038;
saveVarsTmp{1}.Lat.RBY1 = 22.003;
saveVarsTmp{1}.Lat.RBY2 = -13.623;
saveVarsTmp{1}.Lat.RBY3 = -0.0093616;
saveVarsTmp{1}.Lat.RCY1 = 0.98294;
saveVarsTmp{1}.Lat.REY1 = 0;
saveVarsTmp{1}.Lat.REY2 = 0;
saveVarsTmp{1}.Lat.RHY1 = -9.1492E-11;
saveVarsTmp{1}.Lat.RHY2 = 0;
saveVarsTmp{1}.Lat.RVY1 = 22.965;
saveVarsTmp{1}.Lat.RVY2 = 0.37981;
saveVarsTmp{1}.Lat.RVY3 = 1.8552;
saveVarsTmp{1}.Lat.RVY4 = 0.08767;
saveVarsTmp{1}.Lat.RVY5 = -8.8234E-11;
saveVarsTmp{1}.Lat.RVY6 = 0.90374;
saveVarsTmp{1}.Lat.PTY1 = 1.75;
saveVarsTmp{1}.Lat.PTY2 = 1.35;
saveVarsTmp{1}.Roll = struct;
saveVarsTmp{1}.Roll.QSY1 = 0.01;
saveVarsTmp{1}.Roll.QSY2 = 0;
saveVarsTmp{1}.Roll.QSY3 = 0;
saveVarsTmp{1}.Roll.QSY4 = 0;
saveVarsTmp{1}.Align = struct;
saveVarsTmp{1}.Align.QBZ1 = 19.588;
saveVarsTmp{1}.Align.QBZ2 = -4.1671;
saveVarsTmp{1}.Align.QBZ3 = -0.34132;
saveVarsTmp{1}.Align.QBZ4 = -0.023607;
saveVarsTmp{1}.Align.QBZ5 = -0.0793;
saveVarsTmp{1}.Align.QBZ9 = -50;
saveVarsTmp{1}.Align.QBZ10 = 0;
saveVarsTmp{1}.Align.QCZ1 = 1.2012;
saveVarsTmp{1}.Align.QDZ1 = 0.12819;
saveVarsTmp{1}.Align.QDZ2 = -0.0052433;
saveVarsTmp{1}.Align.QDZ3 = -0.099544;
saveVarsTmp{1}.Align.QDZ4 = -15;
saveVarsTmp{1}.Align.QDZ6 = 6.2499E-5;
saveVarsTmp{1}.Align.QDZ7 = 0.00050135;
saveVarsTmp{1}.Align.QDZ8 = -0.28564;
saveVarsTmp{1}.Align.QDZ9 = -0.025056;
saveVarsTmp{1}.Align.QEZ1 = -0.0044308;
saveVarsTmp{1}.Align.QEZ2 = 0.022579;
saveVarsTmp{1}.Align.QEZ3 = -0.16199;
saveVarsTmp{1}.Align.QEZ4 = -0.5576;
saveVarsTmp{1}.Align.QEZ5 = -87.296;
saveVarsTmp{1}.Align.QHZ1 = 0.00082436;
saveVarsTmp{1}.Align.QHZ2 = 0.002733;
saveVarsTmp{1}.Align.QHZ3 = 0.15;
saveVarsTmp{1}.Align.QHZ4 = 0.11608;
saveVarsTmp{1}.Align.SSZ1 = -5.3899E-10;
saveVarsTmp{1}.Align.SSZ2 = -2.2371E-9;
saveVarsTmp{1}.Align.SSZ3 = 3.6029E-8;
saveVarsTmp{1}.Align.SSZ4 = 3.9826E-8;
saveVarsTmp{1}.Align.QTZ1 = 0.3;
saveVarsTmp{1}.Align.MBELT = 7.5;
saveVarsTmp{1}.FLoadMax = 10000;
tire.Value = saveVarsTmp{1};
tire.HasCoderInfo = false;
tire.Description = '';
tire.DataType = 'struct';
tire.Min = [];
tire.Max = [];
tire.DocUnits = '';
clear saveVarsTmp;

total_pitchDamping = Simulink.Parameter;
total_pitchDamping.Value = 22000;
total_pitchDamping.HasCoderInfo = false;
total_pitchDamping.Description = '';
total_pitchDamping.DataType = 'double';
total_pitchDamping.Min = [];
total_pitchDamping.Max = [];
total_pitchDamping.DocUnits = 'N*m/rad';

total_pitchStiffness = Simulink.Parameter;
total_pitchStiffness.Value = 291158.1055;
total_pitchStiffness.HasCoderInfo = false;
total_pitchStiffness.Description = '';
total_pitchStiffness.DataType = 'double';
total_pitchStiffness.Min = [];
total_pitchStiffness.Max = [];
total_pitchStiffness.DocUnits = 'N*m/rad';

total_rollStiffness = Simulink.Parameter;
total_rollStiffness.Value = 138201.9734;
total_rollStiffness.HasCoderInfo = false;
total_rollStiffness.Description = '';
total_rollStiffness.DataType = 'double';
total_rollStiffness.Min = [];
total_rollStiffness.Max = [];
total_rollStiffness.DocUnits = 'N*m/rad';

trackwidth_F = Simulink.Parameter;
trackwidth_F.Value = 1.6;
trackwidth_F.HasCoderInfo = false;
trackwidth_F.Description = '';
trackwidth_F.DataType = 'double';
trackwidth_F.Min = [];
trackwidth_F.Max = [];
trackwidth_F.DocUnits = 'm';

trackwidth_R = Simulink.Parameter;
trackwidth_R.Value = 1.614;
trackwidth_R.HasCoderInfo = false;
trackwidth_R.Description = '';
trackwidth_R.DataType = 'double';
trackwidth_R.Min = [];
trackwidth_R.Max = [];
trackwidth_R.DocUnits = 'm';

unsprung_mass = Simulink.Parameter;
unsprung_mass.Value = 226.704;
unsprung_mass.HasCoderInfo = false;
unsprung_mass.Description = '';
unsprung_mass.DataType = 'double';
unsprung_mass.Min = [];
unsprung_mass.Max = [];
unsprung_mass.DocUnits = 'kg';

wheelbase = Simulink.Parameter;
wheelbase.Value = 2.975;
wheelbase.HasCoderInfo = false;
wheelbase.Description = '';
wheelbase.DataType = 'double';
wheelbase.Min = [];
wheelbase.Max = [];
wheelbase.DocUnits = 'm';

